extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - "node_modules"
  - "dist"
rules:
  sort-imports:
    - error
    - ignoreCase: false
      ignoreDeclarationSort: false
      ignoreMemberSort: false
      memberSyntaxSortOrder:
        - none
        - all
        - multiple
        - single
      allowSeparatedGroups: false
root: true
